### PR TITLE
Source maps support

### PR DESCRIPTION
**Pull request by vxsx**
This is meant to solve #8, however I'm not sure if this is good enough.

If you are interested in these changes, I will adjust readme/examples and add some tests.

Also it would be great to do something with default output, since atm it looks like this, but I'm not sure what to do exactly.
```
...

Collision: #4c4d4d, #4a4a4a
  - #4c4d4d (#4c4d4d) [line: 40:21132 (../../private/sass/settings/_custom.scss:26:19), 40:22723 (../../private/sass/settings/_custom.scss:26:19), 40:22744 (../../private/sass/settings/_custom.scss:26:19), 40:22985 (../../private/sass/settings/_custom.scss:26:19), 40:23006 (../../private/sass/settings/_custom.scss:26:19), 51:1152 (../../private/sass/settings/_custom.scss:26:19)] is too close (1.134761267357035) to #4a4a4a (#4a4a4a) [line: 50:647 (../../private/sass/layout/_header.scss:332:28), 50:679 (../../private/sass/layout/_header.scss:333:31)]

Collision: #282828, #1f1f1f
  - #282828 (#282828) [line: 50:782 (../../private/sass/layout/_header.scss:337:63), 51:765 (../../private/sass/layout/_header.scss:432:23)] is too close (2.8346863735101993) to #1f1f1f (#1f1f1f) [line: 50:2733 (../../private/sass/layout/_header.scss:386:90)]

...
```

Cheers.

### CODE REVIEW

**Comment by FinalAngel** [comment]
gentle bump for merge?

**Comment by SlexAxton** [comment]
I think we always wanted to do a little better than this, but obviously this hasn't happened. Happy to merge this if that'd be better than current.

**Comment by SlexAxton** [comment]
Ah, wait, I think I was thinking of a different PR from a long time ago. This seems more than fine.

**Comment by SlexAxton** [comment]
Went ahead and merged/released. If you wanna add more tests/examples and stuff, I'd be happy to take them, and we can release a patch version.

**Pull request merged**
