### PR TITLE
Rewrite as a PostCSS plugin.

### PR DESCRIPTION
**Pull request by ben-eb**
Fixes https://github.com/SlexAxton/css-colorguard/issues/26.

I changed the logic for how color combinations are logged; now they are done whilst iterating the declarations. This means that you get more warnings than before because they are not consolidated, but I like this output more than the previous one because it is more reusable. Here's a screenshot of the new formatter:

screen shot 2015-09-15 at 16 09 26

Let me know if there's anything that you'd like to change about the new behaviour.

Note that future releases should maintain a changelog to be compatible with the PostCSS plugin guidelines. More details here: https://github.com/postcss/postcss/blob/master/docs/guidelines/plugin.md

### CODE REVIEW

**Comment by jonathantneal** [comment]
:+1: Nice work, Ben! I’d love to use this version, @SlexAxton.

**Comment by SlexAxton** [comment]
Sorry for the delay. This looks great. I'm not really in a great spot to review the postcss specific stuff, but I checked it out and ran some tests, and can generally still follow the few specific parts to actually doing the CIEDE2000 stuff.

I like the new output style much better.

Merging...

**Comment by SlexAxton** [comment]
This is now released as 1.0.0 - I've also added you as a contributor for any future fixes you deem worthwhile. Thanks for your work on this.

(Digging into a bunch of rework->postcss at work at the moment, so maybe I'll even bug you!)

**Comment by ben-eb** [comment]
Thanks! :+1:

**Pull request merged**
